name: Testing Preview Action

on: pull_request

jobs:
  preview:
    name: Preview Testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    ## test publishing with and without this action with my test repo
    - uses: actions/setup-node@v2
    - uses: ./publish-pr-preview
      env:
        NODE_AUTH_TOKEN: ${{ secrets.MYSTERY_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.FRONTSIDEJACK_GITHUB_TOKEN  }}
